//SCOPE : internationalization

export const APP_TEXTS = {
  DEBIT_CARD_HEADER: 'Debit Card',
  AVAILABLE_BALANCE: 'Available balance',
  CURRENCY: 'S$',
  BALANCE_AMOUNT: '3,000',
  TOP_UP_TITLE: 'Top-up account',
  TOP_UP_SUBTITLE: 'Deposit money to your account to use with card',
  WEEKLY_LIMIT_TITLE: 'Weekly spending limit',
  WEEKLY_LIMIT_SUBTITLE: "You haven't set any spending limit on card",
  FREEZE_CARD_TITLE: 'Freeze card',
  FREEZE_CARD_SUBTITLE: 'Your debit card is currently active',
  CARDHOLDER_NAME: 'Mark Henry',
  CARD_NUMBER: '5647   3411   2413   2020',
  CARD_THRU: 'Thru: 12/20',
  CARD_CVV: 'CVV: 456',
  CARD_BRAND: 'VISA',
  CARD_ISSUER: 'aspire',
  HOME_SCREEN: 'Home Screen',
  PAYMENTS_SCREEN: 'Payments Screen',
  CREDIT_SCREEN: 'Credit Screen',
  PROFILE_SCREEN: 'Profile Screen',
  HIDE_CARD_NUMBER: 'Hide Card Number',
  SHOW_CARD_NUMBER: 'Show Card Number',
  GET_NEW_CARD: 'Get New Card',
  GET_NEW_CARD_SUBTITLE: 'Get a new card to continue using your account',
  DEACTIVATED_CARDS: 'Deactivated Cards',
  DEACTIVATED_CARDS_SUBTITLE: 'Your previously deactivated cards',
  DEBIT_CARD_SPENDING_LIMIT: 'Debit card spending limit',
}; 